from enum import Enum


class ArchReviewEvent(str, Enum):
    EVALUATION_STARTED = "EVALUATION_STARTED"
    FITNESS_PASS = "FITNESS_PASS"
    FITNESS_WARN = "FITNESS_WARN"
    FITNESS_FAIL_CRITICAL = "FITNESS_FAIL_CRITICAL"
    REFACTOR_REQUESTS_CREATED = "REFACTOR_REQUESTS_CREATED"
    REFACTOR_DEFERRED = "REFACTOR_DEFERRED"
    REFACTOR_BLOCKED = "REFACTOR_BLOCKED"
    RETRY_THRESHOLD_EXCEEDED = "RETRY_THRESHOLD_EXCEEDED"


class DebtEvent(str, Enum):
    DEBT_TRIAGE = "DEBT_TRIAGE"
    DEBT_DEFER = "DEBT_DEFER"
    DEBT_SCHEDULE = "DEBT_SCHEDULE"
    DEBT_RESOLVE = "DEBT_RESOLVE"
    DEBT_OVERRIDE_ACTIVATE = "DEBT_OVERRIDE_ACTIVATE"
