from enum import Enum


class FoundationEvent(str, Enum):
    FOUNDATION_STARTED = "FOUNDATION_STARTED"
    RESEARCH_RECOMMEND = "RESEARCH_RECOMMEND"
    RESEARCH_NEEDS_MORE = "RESEARCH_NEEDS_MORE"
    RESEARCH_BLOCKED = "RESEARCH_BLOCKED"
    APPROVE_FOUNDATION = "APPROVE_FOUNDATION"
    REVISE_FOUNDATION = "REVISE_FOUNDATION"
    BLOCK_FOUNDATION = "BLOCK_FOUNDATION"
    RETRY_THRESHOLD_EXCEEDED = "RETRY_THRESHOLD_EXCEEDED"
