from enum import Enum


class PMEvent(str, Enum):
    """Typed events for PM transitions."""

    FOUNDATION_GATE_PASSED = "FOUNDATION_GATE_PASSED"
    PHASE1_PROVISIONAL_CHAMPION = "PHASE1_PROVISIONAL_CHAMPION"
    PHASE1_DEFER = "PHASE1_DEFER"
    PHASE1_BLOCK = "PHASE1_BLOCK"
    RESEARCH_TASKS_CREATED = "RESEARCH_TASKS_CREATED"
    LINKED_RESEARCH_ALL_CLOSED = "LINKED_RESEARCH_ALL_CLOSED"
    SYNTHESIS_READY = "SYNTHESIS_READY"
    PHASE2_CHAMPION = "PHASE2_CHAMPION"
    PHASE2_DEFER = "PHASE2_DEFER"
    PHASE2_BLOCK = "PHASE2_BLOCK"
    PHASE2_ESCALATE = "PHASE2_ESCALATE"
    RETRY_THRESHOLD_EXCEEDED = "RETRY_THRESHOLD_EXCEEDED"
