from enum import Enum


class POEvent(str, Enum):
    """Typed events for PO state transitions."""

    ENTERED_PRIORITIZATION = "ENTERED_PRIORITIZATION"
    PRIORITIZATION_CREATE = "PRIORITIZATION_CREATE"
    PRIORITIZATION_DEFER = "PRIORITIZATION_DEFER"
    PRIORITIZATION_REJECT = "PRIORITIZATION_REJECT"
    FEATURE_REQUESTS_COMMITTED = "FEATURE_REQUESTS_COMMITTED"
    RETRY_THRESHOLD_EXCEEDED = "RETRY_THRESHOLD_EXCEEDED"
