from enum import Enum


class DiscoveryState(str, Enum):
    DISCOVERY_IDLE = "DISCOVERY_IDLE"
    DISCOVERY_RUNNING = "DISCOVERY_RUNNING"
    DISCOVERY_COMPLETE = "DISCOVERY_COMPLETE"
    DISCOVERY_HALTED_NO_GATE = "DISCOVERY_HALTED_NO_GATE"
    DISCOVERY_HALTED_NO_FOCUS = "DISCOVERY_HALTED_NO_FOCUS"


TERMINAL_DISCOVERY_STATES = {
    DiscoveryState.DISCOVERY_COMPLETE,
    DiscoveryState.DISCOVERY_HALTED_NO_GATE,
    DiscoveryState.DISCOVERY_HALTED_NO_FOCUS,
}
