from enum import Enum


class FoundationState(str, Enum):
    FOUNDATION_NEEDED = "FOUNDATION_NEEDED"
    FOUNDATION_INTENT_CAPTURE_CREATE = "FOUNDATION_INTENT_CAPTURE_CREATE"
    FOUNDATION_INTENT_CAPTURE_VERIFY = "FOUNDATION_INTENT_CAPTURE_VERIFY"
    FOUNDATION_SHELL_DESIGN_CREATE = "FOUNDATION_SHELL_DESIGN_CREATE"
    FOUNDATION_SHELL_DESIGN_VERIFY = "FOUNDATION_SHELL_DESIGN_VERIFY"
    FOUNDATION_BACKLOG_BUILD_CREATE = "FOUNDATION_BACKLOG_BUILD_CREATE"
    FOUNDATION_BACKLOG_BUILD_VERIFY = "FOUNDATION_BACKLOG_BUILD_VERIFY"
    FOUNDATION_READINESS_ASSESS_CREATE = "FOUNDATION_READINESS_ASSESS_CREATE"
    FOUNDATION_READINESS_ASSESS_VERIFY = "FOUNDATION_READINESS_ASSESS_VERIFY"
    FOUNDATION_HANDOFF_PACK_CREATE = "FOUNDATION_HANDOFF_PACK_CREATE"
    FOUNDATION_HANDOFF_PACK_VERIFY = "FOUNDATION_HANDOFF_PACK_VERIFY"
    FOUNDATION_APPROVED = "FOUNDATION_APPROVED"
    FOUNDATION_BLOCKED = "FOUNDATION_BLOCKED"
    FOUNDATION_NEEDS_HUMAN = "FOUNDATION_NEEDS_HUMAN"


TERMINAL_FOUNDATION_STATES = {
    FoundationState.FOUNDATION_APPROVED,
    FoundationState.FOUNDATION_BLOCKED,
    FoundationState.FOUNDATION_NEEDS_HUMAN,
}
