from enum import Enum


class FoundationState(str, Enum):
    FOUNDATION_NEEDED = "FOUNDATION_NEEDED"
    FOUNDATION_IN_PROGRESS = "FOUNDATION_IN_PROGRESS"
    FOUNDATION_REVIEW = "FOUNDATION_REVIEW"
    FOUNDATION_APPROVED = "FOUNDATION_APPROVED"
    FOUNDATION_BLOCKED = "FOUNDATION_BLOCKED"
    FOUNDATION_NEEDS_HUMAN = "FOUNDATION_NEEDS_HUMAN"


TERMINAL_FOUNDATION_STATES = {
    FoundationState.FOUNDATION_APPROVED,
    FoundationState.FOUNDATION_BLOCKED,
    FoundationState.FOUNDATION_NEEDS_HUMAN,
}
