from enum import Enum


class PMState(str, Enum):
    """Typed PM states for the pilot state machine."""

    PM_QUEUED = "PM_QUEUED"
    PM_PHASE1_VALIDATING = "PM_PHASE1_VALIDATING"
    PM_RESEARCH_PLANNING = "PM_RESEARCH_PLANNING"
    PM_RESEARCH_WAITING = "PM_RESEARCH_WAITING"
    PM_RESEARCH_SYNTHESIZING = "PM_RESEARCH_SYNTHESIZING"
    PM_PHASE2_VALIDATING = "PM_PHASE2_VALIDATING"
    PM_OUTPUT_PUBLISHED = "PM_OUTPUT_PUBLISHED"
    PM_DEFERRED = "PM_DEFERRED"
    PM_BLOCKED = "PM_BLOCKED"
    PM_ESCALATED = "PM_ESCALATED"
    PM_NEEDS_HUMAN = "PM_NEEDS_HUMAN"


TERMINAL_PM_STATES = {
    PMState.PM_OUTPUT_PUBLISHED,
    PMState.PM_DEFERRED,
    PMState.PM_BLOCKED,
    PMState.PM_ESCALATED,
    PMState.PM_NEEDS_HUMAN,
}


def is_terminal_pm_state(state: PMState) -> bool:
    return state in TERMINAL_PM_STATES
